# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flix Part 1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flix Part 1
  Pod "AlamofireImage"
  

  target 'Flix Part 1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Flix Part 1UITests' do
    # Pods for testing
  end

end
